name: sugar-suite

services:
  app:
    image: sugar-suite
    build:
      context: .
      target: builder
    command: sh -c "npm test && npm run preview"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:9000"
    environment:
      - DEBUG=true
      - CI=false
      - NODE_ENV=development

    # https://docs.docker.com/compose/how-tos/file-watch/
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /app
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json

    volumes:
      - /app/node_modules
      - ./:/app

    ports:
      - "8080:8080"
